name:                matrix
version:             0.0.1
synopsis:            Quickly generate matrices and copy them to other formats
license:             GPL-3
author:              Solid
maintainer:          soliditsallgood@mailbox.org
homepage:            https://gitlab.com/slotThe/matrix-converter

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-safe
  -Wno-prepositive-qualified-module
  -Wno-missing-kind-signatures
  -O2

default-extensions:
  - StrictData
  - BlockArguments
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - ScopedTypeVariables

dependencies:
  - base
  - containers
  - brick
  - microlens
  - vty
  - Clipboard

library:
  source-dirs: src

executables:
  matrix:
    source-dirs: app
    main: Main.hs
    dependencies: matrix
    ghc-options:
      -threaded
      -with-rtsopts=-N
